"""empty message

Revision ID: 7a9fd8604657
Revises: 4230829be4ea
Create Date: 2025-02-24 19:08:20.937940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9fd8604657'
down_revision = '4230829be4ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('product_images',
    sa.Column('image_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    op.create_table('promotions',
    sa.Column('promotion_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.Enum('REGULAR', 'PERCENTAGE', 'FIXED', name='discount_type_enum'), nullable=False),
    sa.Column('discount_value', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('promotion_id'),
    sa.UniqueConstraint('promotion_code')
    )
    op.create_table('shipping_information',
    sa.Column('shipping_info_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('shipping_method', sa.String(length=50), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('estimated_delivery', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(), nullable=True),
    sa.Column('shipping_status', sa.Enum('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='shipping_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('shipping_info_id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('orders',
    sa.Column('order_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('order_status', sa.Enum('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='order_status'), nullable=False),
    sa.Column('shipping_address', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('payment_methods',
    sa.Column('payment_method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('card_number', sa.String(length=50), nullable=False),
    sa.Column('expiration_date', sa.String(length=10), nullable=False),
    sa.Column('security_code', sa.String(length=5), nullable=False),
    sa.Column('billing_address', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('payment_method_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=False),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.category_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('shopping_carts',
    sa.Column('shopping_cart_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shopping_quantity', sa.Integer(), nullable=True),
    sa.Column('total_price', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('shopping_cart_id')
    )
    op.create_table('wishlists',
    sa.Column('wishlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('wishlist_id')
    )
    op.create_table('cart_items',
    sa.Column('cart_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('shopping_cart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shopping_cart_id'], ['shopping_carts.shopping_cart_id'], ),
    sa.PrimaryKeyConstraint('cart_item_id')
    )
    op.create_table('order_items',
    sa.Column('order_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=False),
    sa.Column('discount', sa.String(length=100), nullable=True),
    sa.Column('shipping_cost', sa.String(length=100), nullable=True),
    sa.Column('tax', sa.String(length=100), nullable=True),
    sa.Column('discount_type', sa.Enum('REGULAR', 'PERCENTAGE', 'FIXED', name='discount_type'), nullable=True),
    sa.Column('shipping_status', sa.Enum('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='shipping_status'), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_amount', sa.String(length=100), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('payment_status', sa.Enum('SUCCESS', 'FAILED', 'PENDING', 'COMPLETED', 'REFUNDED', 'EXPIRED', 'CAPTURED', name='payment_status'), nullable=False),
    sa.Column('payment_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.PrimaryKeyConstraint('payment_id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('payments')
    op.drop_table('order_items')
    op.drop_table('cart_items')
    op.drop_table('wishlists')
    op.drop_table('shopping_carts')
    op.drop_table('products')
    op.drop_table('payment_methods')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('shipping_information')
    op.drop_table('promotions')
    op.drop_table('product_images')
    op.drop_table('categories')
    # ### end Alembic commands ###
